### ISSUE TITLE
Not compatible with multiprocess/e10s

### ISSUE THREAD

**Issue by EchoDev** [dillbyrne/toggle-cipher-suites#11]
According to the [Add-on Compatibility Reporter](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) Toggle Cipher Suites is not compatible with e10s.  Not sure how accurate the addon is.

Not sure how easy it would be to fix this but it would be nice if the addon could be compatible with e10s to prevent any issues with e10s.

**Comment by dillbyrne** [comment]
Hi  @EchoDev I have tested it here and it works fine. I guess it is simply looking for addons that have the multiprocess flag in the manifest. I have added the flag and I will update the addon on AMO. Thanks for reporting it
