### ISSUE TITLE
Auto update ciphers

### ISSUE THREAD

**Issue by davidhedlund** [dillbyrne/toggle-cipher-suites#5]
I find security.ssl3.dhe_dss_aes_128_sha in about:config but not "dhe_dss_aes_128_sha" in your add-on. Can you please add it?

**Comment by dillbyrne** [comment]
@davidhedlund What version of firefox are you using ? . I do not see `security.ssl3.dhe_dss_aes_128_sha` in firefox 45 or 47 ?

**Comment by davidhedlund** [comment]
Firefox ESR 38.7.1 for Windows was tested.

**Comment by davidhedlund** [comment]
@dillbyrne did you find it?

**Comment by dillbyrne** [comment]
@davidhedlund It used to support the older ciphers but I updated it as ff updated it . When I get a chance I'll add an update to dynamically display the supported ciphers based on what version the user has installed.

**Comment by dillbyrne** [comment]
@davidhedlund the addon now lists whatever ciphers your version of firefox supports. On ff38 for linux I don't have dhe_dss_aes_128_sha however. I'll add an update to AMO later in the day.

**Comment by davidhedlund** [comment]
@dillbyrne Thank you.
