### ISSUE TITLE
corlos marking which ciphers are enabled/disabled

### ISSUE THREAD

**Issue by deathtrip** [dillbyrne/toggle-cipher-suites#8]
How about an option to color the rows based on whether the cipher is enabled or disabled.
For example red color for disabled and green for enabled ciphers.

**Comment by dillbyrne** [comment]
Hi @deathtrip. This could cause problems for colour blind users.  

http://www.colourblindawareness.org/colour-blindness/types-of-colour-blindness/

Also not all colours have the same associations for positive and negative.

 https://graphicdesign.stackexchange.com/questions/6982/except-china-which-country-will-use-red-for-up-and-green-for-down.

As it is now it is neutral and does not cause problems , So I'm inclined to leave it as it is
